[package]
name = "poseidon-transcript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.12.0"
halo2curves = { git = "https://github.com/DanTehrani/halo2curves", branch = "secq256k1" }