[package]
name = "poseidon-transcript"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.12.0"
secq256k1 = { git = "https://github.com/personaelabs/spartan-ecdsa.git", package = "secq256k1" }